# Collector specific configuration
download_url: "https://live-ngoaidmap.pantheonsite.io/ngo-aid/member-updates"
hxltags:
  "Title": "#activity+title"
  "Member Organization": "#org+name"
  "Date": "#date"
  "Summary": "#description"
  "Content": "#activity+content"
  "Topics": "#activity+topic"
  "Working Groups": "'activtiy+working_group"
  "Sectors": "#sector"
  "Funding Type": "#org+funder+type"
  "Other Tags": "#meta+tags"
  "Author": "#meta+author"
  "Status": "#status"
  "iso3": "#country+code"

tag_mapping:
  "financial sector": "financial institutions"
  "local economic development": "economics"
  "peacebuilding": "peacekeeping"
  "rule of law": "governance and civil society"
  "prevention from sexual exploitation": "sexual violence and abuse"
  "monitoring": "monitoring and evaluation"
  "covid-19 response": "covid-19"
  "global health": "health"
  "hygiene (wash)": "water sanitation and hygiene - wash"
  "local governance": "governance and civil society"
  "peace": "peacekeeping"
  "higher education": "education"
  "harassment": "human rights"
  "infrastructure development": "facilities and infrastructure"
  "disaster preparedness": "disaster risk reduction - drr"
  "health systems support": "health services - healthcare"
  "reconciliation": "peacekeeping"
  "good governance": "governance and civil society"
  "economic opportunity": "economics"
  "democracy": "governance and civil society"
  "advocacy": "human rights"
  "abuse": "sexual violence and abuse"
  "security - general": "security"
  "economic development": "economics"
  "conflict mitigation": "violence and conflict"
